group:
  - name: common-files
    repos:
      - andraderenew/structural-mri_cat12-vs-freesurfer_oasis1
      - andraderenew/fmri-task_spm_firstlevel_auditory
      - andraderenew/fmri-rest_fsl-graphs_braph_adhd200-preproc
      - andraderenew/dti_fsl-dtifit_tutorial
      - andraderenew/eeg_erps-tf_eeglab-fieldtrip_sternberg
      - andraderenew/eeg_sources-connectivity_loreta-brainstorm_pte
      - andraderenew/meg_erfs-sources_brainstorm_median-nerve
      - andraderenew/pet_suvr-pvc_spm_petpve12_oasis3
    files:
      # SIEMPRE (seguros e idénticos)
      - source: .github/PULL_REQUEST_TEMPLATE.md
        dest: .github/PULL_REQUEST_TEMPLATE.md
      - source: .github/ISSUE_TEMPLATE/
        dest: .github/ISSUE_TEMPLATE/
        deleteOrphaned: false
      - source: LICENSE
        dest: LICENSE
      - source: .gitignore
        dest: .gitignore

      # BROADCAST UNA SOLA VEZ
      - source: env/TOOL_VERSIONS.md
        dest: env/TOOL_VERSIONS.md
